name: "Build Pull Request"

on:
  pull_request:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.310'

    - name: Build
      run: |
        dotnet build Hello/Hello.csproj
